# Generated by Django 4.1.13 on 2024-10-22 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_subscriptionplan_customer_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='customer_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
